Fix doxygen typo and other various typos
Beep6581/RawTherapee pull request #5573
Opened 2019-12-20 01:46 UTC by luzpaz

2019-12-20 06:58 UTC, Floessie requested changes
Thanks, @luzpaz. There's one little change needed.

2019-12-20 06:58 UTC, Floessie commented on rtengine/color.h
> +    * @param correctionHuechroma hue correction depending on chromaticity (saturation), in radians [0 ; 0.45] (return value)
It's even `correctionHueChroma`.

2019-12-20 11:08 UTC, luzpaz commented on rtengine/color.h
> +    * @param correctionHuechroma hue correction depending on chromaticity (saturation), in radians [0 ; 0.45] (return value)
Fixed: c5d2e00

2019-12-20 11:09 UTC, luzpaz commented
Correct requested feedback + found 2 more typos 7f425e7

2019-12-20 12:39 UTC, merged

2020-06-17 12:00 UTC, Floessie commented
@luzpaz Could you give current `dev` another sweep?

2020-06-19 15:58 UTC, luzpaz commented
@Floessie Done, please see https://github.com/Beep6581/RawTherapee/pull/5804