Build-unique information
Beep6581/RawTherapee pull request #5648
Opened 2020-02-09 13:11 UTC by Benitoite

Modifies UpdateInfo.cmake and AboutThisBuild.txt.in to gather and display some build-unique information for tracking multiple builds generated from the same commit.

2020-02-09 21:04 UTC, heckflosse commented
@Benitoite Builds fine on Windows, but this is quite annoying:

```
Version: 5.2-3420-g80eb85215
```

2020-02-09 22:02 UTC, Benitoite commented
That looks wierd.  The version number looks low.
Mac result:
```
Version: 5.8-20-g97dfa4e4a
Branch: dev
Commit: 97dfa4e4a
Commit date: 2020-02-07
Compiler: clang 11.0.0.11000033
Processor: generic x86
System: Apple
Bit depth: 64 bits
Gtkmm: V3.24.2
Lensfun: V0.3.95.0
Exiv2: V
Build type: release
Build flags: -Wno-deprecated-register -Wno-unused-command-line-argument -std=c++11 -std=c++11 -mtune=generic -Werror=unused-label -Werror=delete-incomplete -mmacosx-version-min=10.9 -flto -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -Xpreprocessor -fopenmp /opt/local/lib/libomp.dylib -I/opt/local/include -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:  -mtune=generic -headerpad_max_install_names -flto
OpenMP support: ON
MMAP support: ON
Build OS: Darwin 19.3.0 x86_64
Build date: Sun, 09 Feb 2020 21:54:45 +0000 ZULU
Epoch: 1581285285
UUID: c1d2bd76-3f5a-4e74-8660-4ab50e6692bb
```

2020-02-09 22:11 UTC, heckflosse commented
@Benitoite 

I built on windows from a fresh clone of your fork and branche...

2020-02-09 22:37 UTC, Benitoite commented
https://github.com/Beep6581/RawTherapee/compare/dev...Benitoite:patch-23

@heckflosse be sure to `git checkout patch-23`

2020-02-09 23:35 UTC, heckflosse commented
@heckflosse be sure to git checkout patch-23

I did

2020-02-10 01:58 UTC, Benitoite commented
Ok for some reason you need to fast forward.  I originally forked during 5.2 and that’s where the default branch is. 
```
git fetch 
git pull
git checkout 1925e821b37f56cbdfb5fb5676b44ed6fa8980c4
```

2020-02-10 14:21 UTC, Benitoite commented
@heckflosse Or use Beep6581/RawTherapee@dev and bring in: https://patch-diff.githubusercontent.com/raw/Beep6581/RawTherapee/pull/5648.patch

2020-02-10 14:22 UTC, Benitoite commented
btw @agriggio commented these out in ART; I wonder if there was an issue caused?

2020-02-10 16:00 UTC, Beep6581 commented on AboutThisBuild.txt.in
> +Build Epoch: ${BUILDINFO_EPOCH}
@Benitoite `s/Epoch/epoch/`

2020-02-10 17:47 UTC, Benitoite commented on AboutThisBuild.txt.in
> +Build Epoch: ${BUILDINFO_EPOCH}
👍

2020-02-20 12:22 UTC, Beep6581 commented
@Benitoite as I see new daily commits to this branch, let us know when this PR is ready for merging.

2020-02-21 10:29 UTC, Benitoite commented
@Beep6581 This PR is ready

2020-02-21 23:05 UTC, Beep6581 commented
@Benitoite have you seen my code comments, e.g. about using <tab>?

2020-02-25 20:38 UTC, merged

2020-02-25 20:40 UTC, Beep6581 requested changes

2020-02-25 20:40 UTC, Beep6581 commented on UpdateInfo.cmake
> +
@Benitoite get rid of whitespace (leave newline though)

2020-02-25 20:40 UTC, Beep6581 commented on UpdateInfo.cmake
> +    message(STATUS "    Build OS:   ${BUILDINFO_OS}")
Use tab character here instead of space characters, same as in the lines above:
- single tab before "Build OS"
- as many tabs as necessary after, to align `${BUILDINFO_OS}` with the values from the lines above.

Ditto for the three lines below.

2020-02-25 20:40 UTC, Beep6581 commented on UpdateInfo.cmake
> +    message(STATUS "    Build OS:   ${BUILDINFO_OS}")
@Benitoite if your editor doesn't make this possible, I can happily do it for you after merging if you like?

2020-02-25 20:40 UTC, Beep6581 commented on AboutThisBuild.txt.in
> +Build date: ${BUILDINFO_DATE} ZULU
@Benitoite  "Zulu" (not capitalized) is better known as UTC.

2020-02-25 20:41 UTC, Beep6581 commented
Tabs fixed in cb0f81d0a

2020-02-25 20:42 UTC, Beep6581 commented
Ugh, seems I didn't press the magic "submit" button for my review several days ago...

2020-02-26 07:48 UTC, Benitoite commented
@Beep6581 Many thanks for helping with the tab issues.  I appreciate the code comments you did make.