Do not set math errno
Beep6581/RawTherapee pull request #5742
Opened 2020-05-07 13:33 UTC by heckflosse

In RT we never check [math errno](http://www.cplusplus.com/reference/cerrno/errno/).
Some functions (for example std::sqrt) set errno and because they have to to that, loops calling such functions will not be vecorized by the compiler.

This example-code will not be vectorized:
```C++
#include <cmath>

void sqrtrow(float *data, int width) {

    for (int i = 0; i < width; ++i) {
        data[i] = std::sqrt(data[i]);
    }
}
```

If we use `-fno-math-errno`, the errno will not be set and the loop will be vecorized by the compiler

Any objections to use this flag?

2020-05-07 14:17 UTC, heckflosse commented
From [here](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html)

```
-fno-math-errno

    Do not set errno after calling math functions that are executed with a single instruction, e.g., sqrt. A program that relies on IEEE exceptions for math error handling may want to use this flag for speed while maintaining IEEE arithmetic compatibility.

    This option is not turned on by any -O option since it can result in incorrect output for programs that depend on an exact implementation of IEEE or ISO rules/specifications for math functions. It may, however, yield faster code for programs that do not require the guarantees of these specifications.

    The default is -fmath-errno.

    On Darwin systems, the math library never sets errno. There is therefore no reason for the compiler to consider the possibility that it might, and -fno-math-errno is the default.
```

2020-05-07 15:47 UTC, Thanatomanic commented
Seems all right. So I take it we don't use "IEEE exceptions for math error handling"?

2020-05-07 15:54 UTC, heckflosse commented
> So I take it we don't use "IEEE exceptions for math error handling"?

Correct, that would not play well with crunching numbers in vecorized code.

2020-05-08 09:49 UTC, Floessie commented
* Debian Testing AMD64, GCC 9.3: :heavy_check_mark: 
* Debian Testing AMD64, GCC 10.0: :white_check_mark: (there's an unrelated compiler bug)
* Debian Testing AMD64, Clang 10.0: :heavy_check_mark: 
* Debian Buster i386, GCC 8.3: :heavy_check_mark: 
* Debian Unstable PPC, GCC 9.3: :heavy_check_mark: 
* Debian Unstable PPC, GCC 10.1: :heavy_check_mark: 
* Debian Unstable PPC, Clang 10.0: :heavy_check_mark: 
* Debian Unstable PPC64, GCC 10.1: :heavy_check_mark: 

I don't see any reason for not adding the parameter also to `CMAKE_C_FLAGS`.

2020-05-08 09:50 UTC, Floessie requested changes
`CMAKE_C_FLAGS` should also be tweaked.

2020-05-08 12:03 UTC, merged