Perspective tool: Improve control lines user experience
Beep6581/RawTherapee pull request #6268
Opened 2021-05-31 01:13 UTC by Lawrence37

Makes the "apply" and "delete all" sensitive or insensitive based on the number of control lines and adds extra tool-tip text to explain why correction cannot be applied.

Closes #6250.

2021-05-31 06:10 UTC, Floessie requested changes
Some minor cleanups requested.

2021-05-31 06:10 UTC, Floessie commented on rtgui/controllines.cc
> +size_t ControlLineManager::getHorizontalCount(void) const
Please turn that into `std::size_t ControlLineManager::getHorizontalCount() const`. See [std::size_t](https://en.cppreference.com/w/cpp/types/size_t) for appropriate includes (often, they are already in place).

2021-05-31 06:10 UTC, Floessie commented on rtgui/controllines.cc
> +size_t ControlLineManager::getVerticalCount(void) const
Dito.

2021-05-31 06:10 UTC, Floessie commented on rtgui/controllines.h
> +    size_t horizontalCount, verticalCount;
Dito.

2021-05-31 06:10 UTC, Floessie commented on rtgui/perspective.cc
> +    const auto &tooltip = M("GENERAL_APPLY")
Why `const &` on temporary? It's valid, but makes no sense here. If `set_tooltip_text()` takes the string by value, make it `auto` and `std::move()` it in the call, else make it `const auto`.

2021-05-31 06:10 UTC, Floessie commented on rtgui/perspective.cc
> +void PerspCorrection::updateApplyDeleteButtons(void)
Please no `void` parameter. This is so K&R-C-ish... :wink:

2021-05-31 06:10 UTC, Floessie commented on rtgui/perspective.h
> +    void updateApplyDeleteButtons(void);
Remove the `void` parameter.

2021-05-31 18:25 UTC, Lawrence37 commented
@Floessie I made changes based on your comments.

2021-06-01 06:50 UTC, Floessie approved these changes
@Lawrence37 Very nice! :+1: You even caught some more `size_t`s than I found. And the additional constants are helping as well.

2021-06-03 04:35 UTC, Thanatomanic commented
@Lawrence37 :+1: for merge!

2021-06-04 04:37 UTC, merged