Path filter in dynamic profile panel
Beep6581/RawTherapee pull request #6284
Opened 2021-06-18 15:28 UTC by nicolas-t

Hello,

I started working on adding path filter to the dynamic profile panel.
I don't think I have enough knowledge to do more, so if you like this feature please feel free to finish the job.

Related issue: https://github.com/Beep6581/RawTherapee/issues/6281

2021-06-18 18:38 UTC, Thanatomanic commented
Thanks @nicolas-t for working on your own idea! Let us know when there's something to be tested or you need advice.

2021-06-18 19:30 UTC, nicolas-t commented
Hello @Thanatomanic  :)

I'm having trouble accessing the filename in the `matches` function here : 
https://github.com/Beep6581/RawTherapee/blob/1e797f11e288d0f3dd6bd4e1e4464d9f869ab430/rtengine/dynamicprofile.cc#L89

--- 

In this function I think I have `inputFile` which is the path i'm looking for: 
https://github.com/Beep6581/RawTherapee/blob/b35e0d82694c3d5a80c5decdcd2ddb096f505a07/rtgui/main-cli.cc#L744

But, should I pass it as the second argument of `loadDynamicProfile`, and then pass it again as the second argument of [`rule.matches`](https://github.com/Beep6581/RawTherapee/blob/b35e0d82694c3d5a80c5decdcd2ddb096f505a07/rtengine/profilestore.cc#L524) ?

Seems better to me to store the filename in the `FramesMetaData`/ `FramesData`, but I'm not sure how.


Also, I never did any c++, how can I dump/echo the value of a variable ? 
 
Thanks for you help.

2021-06-19 21:56 UTC, Lawrence37 commented
Hi.
I don't think the file name goes in the metadata, so passing it as an argument is the better option. You can inspect variable values with `std::cout`/`printf()` or by using a debugger such as GDB on the debug build.

2021-06-20 15:45 UTC, nicolas-t commented
Hello @Lawrence37 !
I just pushed 2 commits, I'm passing the filename as the second argument.
App is working normally, and my dynamic profile is well applied depending on filename and path.

Aside from this I tried outputing the filename here : 
https://github.com/Beep6581/RawTherapee/pull/6284/files#diff-bc5e968d23075d5dae37c689a2080f5441c91eb1d3618ab661af1be30cad5c7dR740

But nothing is showing up the terminal.
I'm compiling like this : 
`~/programs/code-rawtherapee/tools/build-rawtherapee -b -d`

And running like this : 
`~/programs/rawtherapee-dev-debug/rawtherapee`
Out of curiosity: where is the output supposed to appear ? 

Anyway, the feature is working on my side, can you test and review my code ?

Thanks

2021-06-20 23:30 UTC, Lawrence37 commented
The output appears in the terminal. You've placed the code in the CLI version of RT, so it will only appear if you run `rawtherapee-cli` instead of `rawtherapee`.

I briefly tested this feature and it works fine. I will add my code review comments shortly.

2021-06-21 00:05 UTC, Lawrence37 requested changes, later dismissed

2021-06-21 00:05 UTC, Lawrence37 commented on rtdata/languages/English (US)
> +!EXIFFILTER_PATH;Path
This is usually added by running a script, but I think it's fine? Ping @Beep6581.

2021-06-21 00:05 UTC, Lawrence37 commented on rtdata/languages/default
>  EXIFFILTER_SHUTTER;Shutter
I'm concerned that "Path" is a little vague. Something like "File path" is more clear.

2021-06-21 00:05 UTC, Lawrence37 commented on rtgui/main-cli.cc
> +            std::cout << "loading file: " << inputFile << std::endl;
The file isn't being loaded here.

2021-06-24 04:55 UTC, Lawrence37 reviewed
@nicolas-t This looks good.

Should this be included in 5.9? It's a small change but the beta version is almost here and the default language file is under review.

2022-12-31 09:52 UTC, merged

2022-12-31 09:52 UTC, Thanatomanic commented
@nicolas-t Thanks for the work and the patience!