Add default spot size control
Beep6581/RawTherapee pull request #6371
Opened 2021-09-30 12:28 UTC by jonathanBieler

This adds a control for the default size of spot in the spot removal tool. When I remove dust from negative the default size is too large and changing it for every spot quickly gets old.

I'm not sure if I really need the empty `adjusterChanged` method but I didn't manage to compile without. 

![spot_size](https://user-images.githubusercontent.com/5859344/135453636-86513a81-84e3-4e05-b0d2-b9acc8b80df8.JPG)

2021-10-10 00:52 UTC, Lawrence37 requested changes

2021-10-10 00:52 UTC, Lawrence37 commented on rtdata/languages/Francais
> +TP_SPOT_DEFAULT_SIZE;Taille par défault des points
Move this up so that it is in alphabetical order. Also add the English version to the default language file.

2021-10-10 00:52 UTC, Lawrence37 commented on rtgui/spot.cc
> +    spotSize = Gtk::manage(new Adjuster(M("TP_SPOT_DEFAULT_SIZE"), 5, 50, 1, 25));
Change the min and max values to `SpotParams::minRadius` and `SpotParams::maxRadius`.

2021-10-10 00:52 UTC, Lawrence37 commented on rtgui/spot.h
> +class Spot : public ToolParamBlock, public FoldableToolPanel, public AdjusterListener, public rtengine::TweakOperator, public EditSubscriber
I think this may not be necessary. Try reverting this and removing the `adjusterChanged` function.

2021-10-10 00:52 UTC, Lawrence37 commented on rtgui/spot.h
> +    rtengine::ProcEvent EvspotSize;
This event can probably be removed because it doesn't seem to do anything.

2021-10-21 12:02 UTC, jonathanBieler commented
@Lawrence37 thanks for the review, I've made these changes.

2021-10-23 19:08 UTC, Lawrence37 approved these changes

2021-10-23 19:14 UTC, Thanatomanic commented on rtdata/languages/default
> +TP_SPOT_DEFAULT_SIZE;Default point size
@jonathanBieler Can you change this to "Default spot size" please?

2021-12-16 06:29 UTC, Thanatomanic commented
@jonathanBieler If you could address my tiny comment, we can merge this

2022-03-26 10:44 UTC, merged