Release 5.9-rc1
Beep6581/RawTherapee pull request #6596
Opened 2022-10-07 10:26 UTC by Beep6581

2022-10-07 11:04 UTC, Thanatomanic commented
Looks good! Would you please also document the steps you have taken so far, for future reference? Perhaps just elaborate things on https://rawpedia.rawtherapee.com/How_to_release_RawTherapee.

2022-10-07 13:28 UTC, jade-nl commented
Just gave this 5.9 rc1 appimage a quick try and it runs smoothly on a, somewhat older, Linux (Debian 10.13/Buster) box.

2022-10-07 21:18 UTC, Beep6581 commented
@Thanatomanic I don't think I did anything not in that document. Going through the log and looking at some patches took a while. It was good to catch up, and you did a good job, e.g. when you reworked the logo. I used my old laptop with the non-"fixed" version of `sort`. Speaking of that, we might need to drop the reliance on natural-sort since the coreutils devs consider having it drop lines [the correct behavior](https://github.com/Beep6581/RawTherapee/pull/6503#issuecomment-1262042640). Next I'll try to update the screenshots in the appdata file, and then the daunting task of setting up and documenting the website deployment and update.

2022-10-08 18:37 UTC, Lawrence37 requested changes
@Beep6581 Spotted a few issues in the release notes.

2022-10-08 18:37 UTC, Lawrence37 commented on RELEASE_NOTES.txt
> +- The White Balance tool (Color tab) received new automatic white balance methods.
Only one new method was added (temperature correlation).

2022-10-08 18:37 UTC, Lawrence37 commented on RELEASE_NOTES.txt
> +    - Nikon Z 7_2
```suggestion
    - Nikon Z 6II
    - Nikon Z 7II
```
https://imaging.nikon.com/lineup/mirrorless/index.htm

2022-10-08 18:37 UTC, Lawrence37 commented on RELEASE_NOTES.txt
> +    - Nikon Z fc
```suggestion
    - Nikon Z fc
```

2022-10-08 18:37 UTC, Lawrence37 commented on RELEASE_NOTES.txt
> +    - OLYMPUS STYLUS1,1s
```suggestion
    - OLYMPUS Stylus 1
    - OLYMPUS Stylus 1s
```
I think this is "Stylus 1" and "Stylus 1s"

2022-10-08 18:37 UTC, Lawrence37 commented on RELEASE_NOTES.txt
> +    - RICOH PENTAX K-3 MARK III
```suggestion
    - RICOH PENTAX K-3 Mark III
```
https://us.ricoh-imaging.com/wp-content/uploads/2019/01/k-3-3.pdf

2022-10-08 18:37 UTC, Lawrence37 commented on RELEASE_NOTES.txt
> +    - Canon EOS 1DX Mark III
```suggestion
    - Canon EOS 1DX Mark III
```

2022-10-08 18:37 UTC, Lawrence37 commented on RELEASE_NOTES.txt
> +    - Canon EOS 5D Mark II
```suggestion
    - Canon EOS 5D Mark II
```

2022-10-08 18:37 UTC, Lawrence37 commented on RELEASE_NOTES.txt
> +    - Canon EOS R3, R7 and R10.
```suggestion
    - Canon EOS R3, R7 and R10
```

2022-10-08 18:37 UTC, Lawrence37 commented on RELEASE_NOTES.txt
> +    - Canon EOS-1Ds Mark II
```suggestion
    - Canon EOS-1Ds Mark II
```

2022-10-08 18:37 UTC, Lawrence37 commented on RELEASE_NOTES.txt
> +    - Fujifilm X-T4
```suggestion
    - Fujifilm X-T4
```

2022-10-08 18:37 UTC, Lawrence37 commented on RELEASE_NOTES.txt
> +    - Nikon D5100
```suggestion
    - Nikon D5100
```

2022-10-08 18:37 UTC, Lawrence37 commented on RELEASE_NOTES.txt
> +    - OLYMPUS E-M5MarkIII
```suggestion
    - OLYMPUS E-M10 Mark IV
    - OLYMPUS E-M1 Mark III
    - OLYMPUS E-M1X
    - OLYMPUS E-M5 Mark II (DCP)
    - OLYMPUS E-M5 Mark III
```

2022-10-08 18:37 UTC, Lawrence37 commented on RELEASE_NOTES.txt
> +    - Samsung Galaxy S7
```suggestion
    - Samsung Galaxy S7
```

2022-10-08 18:43 UTC, Lawrence37 commented on RELEASE_NOTES.txt
> +    - Sony ILCE-7M4
```suggestion
    - Sony ILCE-7M4
```

2022-10-13 14:48 UTC, Lawrence37 approved these changes

2022-10-22 23:21 UTC, Lawrence37 commented on rtdata/languages/Japanese
> -#12 2022-06-04 Yz2house
Was this unintentionally removed?

2022-11-27 19:30 UTC, merged