Support for saving TIFFs as BigTIFF (#6690)
Beep6581/RawTherapee pull request #6696
Opened 2023-03-01 11:56 UTC by Floessie

Hello RawTherapists,

as requested in #6690 I've extended saving TIFFs in [BigTIFF](https://en.wikipedia.org/wiki/TIFF#BigTIFF) format, which was straightforward. Please check if I missed something.

Best,
Flössie

2023-03-02 06:23 UTC, Lawrence37 requested changes

2023-03-02 06:23 UTC, Lawrence37 commented on rtgui/saveformatpanel.cc
> +    bigTiff = new Gtk::CheckButton (M("SAVEDLG_BIGTIFF"));
Gtk::manage

2023-03-02 06:30 UTC, Lawrence37 commented
Functionality-wise, everything looks good. I did notice some of the EXIF is missing when read with exiftool. It also shows this message
`Warning                         : Truncated ExifOffset directory`
I don't know if this is a RawTherapee problem, a BigTIFF problem, or an exiftool problem. Exiv2 is not able to read BigTIFF.

2023-03-02 07:57 UTC, Floessie commented on rtgui/saveformatpanel.cc
> +    bigTiff = new Gtk::CheckButton (M("SAVEDLG_BIGTIFF"));
@Lawrence37 Thanks for review! :+1: 

In `dev` both `jpegQual` and `tiffUncompressed` aren't managed. You seem to indicate there's no reason for this, so I'll change them to `Gtk::manage()` as well. Okay?

2023-03-02 08:01 UTC, Floessie commented
@Lawrence37 I'll have a look at the way the EXIF is patched in in `saveTIFF()`...

2023-03-02 08:13 UTC, Floessie commented on rtgui/saveformatpanel.cc
> +    bigTiff = new Gtk::CheckButton (M("SAVEDLG_BIGTIFF"));
@Lawrence37 It's quite revealing to search for ` = new Gtk::`. :raised_eyebrow:

2023-03-02 09:23 UTC, Floessie commented
@Lawrence37 I'm afraid we won't be able to support BigTIFF EXIF with our handmade `rtexif` without a lot of work. See the technical details [here](http://www.bigtiff.org/), which has a comparison about the directory formats. In RT `TagDirectory::write()` etc. make assumptions about sizes that only fit for classic TIFF. All those assumptions must be revised.

You're more into the Exiv2 toppic than I. Would it be easier to support large offset EXIFs with Exiv2?

2023-03-02 09:42 UTC, kmilos commented
Exiv2 does not currently support BigTIFF and a substantial rewrite is needed.

2023-03-02 10:06 UTC, Floessie commented
@kmilos Thanks for the info. I did some research in parallel and came to the [same conclusion](https://github.com/Exiv2/exiv2/issues/1329).

2023-03-02 10:14 UTC, Floessie commented
@Beep6581 @Thanatomanic How do we proceed?

1. Add BigTIFF support as is without EXIF export and add that ("without metadata") to the checkbox label.
2. Pimp our `rtexif` for large offsets so BigTIFF is fully supported. It is doable but takes some hours of work.
3. Drop this PR as we won't be able to support metadata with the Exiv2 branch anyway.
4. Support the Exiv2 folks with their BigTIFF implementation.
5. Do something else.

Best,
Flössie

2023-03-02 15:41 UTC, Beep6581 commented
@Floessie I think my reply will come as no surprise :)

Personally, I would only use BigTIFF (probably unknowingly) when working with stitched panoramas. Having metadata would be preferable, but not having it would still be better than not being able to save the panorama at all.

RT should not put any resources into the current `rtexif` code and finally fully focus on Exiv2. If possible for the Exiv2 branch to support BigTIFF with some work, great. Adding BigTIFF support without metadata is entirely acceptable, as long as it's documented (and either visible via a label in the GUI somewhere, or via a tooltip).

Best regards from a thawing Sweden

2023-03-02 21:58 UTC, Lawrence37 approved these changes

2023-03-03 07:19 UTC, Floessie commented
@Beep6581 Well, I feared an "all or nothing" reply from you, so I'm positively surprised. :wink:

I'll fix the label and prevent the EXIF hack in `saveTIFF()` from overwriting the header ASAP and merge the PR (if there are no objections) on Sunday.

2023-03-05 10:23 UTC, merged