"Real" Hi-DPI support for RawTherapee GUI - Part 1
Beep6581/RawTherapee pull request #6830
Opened 2023-08-28 15:22 UTC by Pandagrapher

This PR brings "real" Hi-DPI support for RawTherapee GUI. Except for image related custom widgets (ex: thumbnail, image area, ...), all the RT GUI has been migrated to handle Hi-DPI.

Example 1:
- Before (RT 5.9):
![image](https://github.com/Beep6581/RawTherapee/assets/40305292/1953de1e-8507-4a4c-b598-0df596728203)
- After (this PR):
![image](https://github.com/Beep6581/RawTherapee/assets/40305292/e8aa9910-82d1-47f1-a16b-6dccd36a9aa9)

Example 2:
- Before (RT 5.9):
![image](https://github.com/Beep6581/RawTherapee/assets/40305292/001f6765-f21e-464b-8d34-20f84c00970b)
- After (this PR):
![image](https://github.com/Beep6581/RawTherapee/assets/40305292/0efcdc9e-3ba8-4707-b6ff-2898ad45546c)

This PR has been tested with the following environnements:
- Windows 11, 2K screen
- MacOS Ventura, MacBook Retina screen
- Debian Testing (VM), MacBook Retina screen

In a second PR, I will work on the image related custom widgets.

Detailed list of changes:
- Icons are now managed as Gtk Icon Theme. Surfaces are directly generated from .svg files and takes into account the DPI of the screen to avoid "blur" effect. To avoid reaching GDI limit on Windows, surfaces are buffered and reused (I hope it is handled differently in Gtk4...). Large parts of GUI code have been updated.
- Custom widget `on_draw` functions have been updated to handle Hi-DPI during drawing.
- Bug fix with Histogram panel widget: When loading an image, raw histogram data were incorectly not set (but provided)
- Bug fix with Histogram panel widget: Fixes incorrect curve scaling in raw histogram mode (was incorrectly scaled using luma and chroma data)
- Bug fix loading icon cache data: With some versions of Glib/Glibmm library on MacOS, Glib::KeyFile "load_from_file" function does not raise a Glib::Error but another exception. This causes cached data not saved on disk (and thumbnails not displayed in explorer). Adds robustness testing if file is present first before calling the function
- Bug fix loading dynamic profiles data: Same issue with Glib::KeyFile "load_from_file" funtion
- Cleanup of RT theme management
- Simplification of font size management as Pango/Gtk directly manage pt/px conversion based on screen DPI
- Bug fix in Preference panel: If panel is closed with "cancel" button, font size was not reinitialized to previously saved one
- Bug fix in `RawTherapee.css` theme: Font size was sprecified in css file and so user choice could be ignored

2023-08-28 16:24 UTC, Benitoite commented
I noticed in step https://github.com/Beep6581/RawTherapee/actions/runs/6001775737/job/16276688899#step:5:82
the requested version of RSVG-2 was lower than provided by the runner, which is Ubuntu 20.04.  Ubuntu 22.04 https://packages.ubuntu.com/search?suite=jammy&searchon=names&keywords=librsvg2-dev seems to provide that minimum version, with 22.10 and 23.04 providing even more recent RSVG-2.

2023-08-28 16:35 UTC, Pandagrapher commented
> I noticed in step https://github.com/Beep6581/RawTherapee/actions/runs/6001775737/job/16276688899#step:5:82 the requested version of RSVG-2 was lower than provided by the runner, which is Ubuntu 20.04. Ubuntu 22.04 https://packages.ubuntu.com/search?suite=jammy&searchon=names&keywords=librsvg2-dev seems to provide that minimum version, with 22.10 and 23.04 providing even more recent RSVG-2.

Hi @Benitoite 
Yes I noticed that. I don't know why we don't use Ubuntu 22.04 LTS for the AppImage build (CodeQL build uses this version and correct librsvg library version is available). Using Ubuntu 22.04 LTS will also allow using a recent exiv2 package (instead of building it in the AppImage build). If it's ok I can update the AppImage workflow in a commit

BTW. I don't think this PR impacts your script for the MacOS build. Do not hesitate to check :)

Pierre

2023-08-28 20:01 UTC, Lawrence37 commented
The reason to use Ubuntu 20.04 is to maximize compatibility. Essentially, new OSs have backwards compatibility with old AppImage components, but old OSs don't necessarily have forwards compatibility with new AppImage components. See this comment for more information:
https://github.com/Beep6581/RawTherapee/issues/6567#issuecomment-1229066766

2023-08-29 14:41 UTC, Pandagrapher commented
@Lawrence37 Thanks for the details
So, if I have understood well, if we want to keep Ubuntu 20.04 and solve the build issue, we have to build from source a most recent version of librsvg2 and install it (as it is done for exiv2)?

2023-08-29 20:27 UTC, Lawrence37 commented
We just need to install a version of the library which works with this branch. It doesn't have to be the latest version and we can use pre-built binaries from a trustworthy source.

2023-08-30 09:09 UTC, Benitoite commented
![Screenshot 2023-08-30 015702](https://github.com/Beep6581/RawTherapee/assets/17919239/5d11d346-12cb-4a66-bb12-1b4a75e220a6)
Running the generated Windows artifact, 4k/UHD screenshot

2023-09-05 04:26 UTC, Lawrence37 commented
Just wondering how much the icons and text are scaled. Since GTK is handling it, am I correct to think the icons are scaled using the GDK scale (corresponding to the GDK_SCALE environment variable) and text is scaled according to the DPI (adjustable with the GDK_DPI_SCALE environment variable)?

Trying it briefly on Linux, hi-dpi seems to be working well. I noticed just one problem with the Favorites tab settings in preferences. The widgets are very slim. When I designed them, I used the DPI to set their widths. I hindsight, it would have been better to use one of those two panel resizable widgets.

2023-09-05 11:03 UTC, Pandagrapher commented
@Lawrence37 
How it works:
Gtk icon sizes correponds to a pixel size given for a 96 DPI reference (i.e. default Cairo DPI). Text sizes in pt corresponds to a pixel size given for a 72 DPI reference (i.e. default Pango DPI). GDK retrieves DPI data based on OS parameters and so scales up/down the pixel size of GUI elements based on their corresponding DPI reference (refer to notes in `rtscalable.h`).

Thanks for the testing :). I have fixed the Favorite tab settings issue: tab widgets are now dynamically sized based on Preferences window one.

Pierre

2023-09-10 00:09 UTC, Lawrence37 commented
The AppImage build failed because it couldn't find the application icon:
`ERROR: Could not find icon executable for Icon entry: rawtherapee`
The icon file is picked up from the .desktop file:
`Icon=rawtherapee`

A `dev` build installs these files with the word "rawtherapee" in it (`find . -name 'rawtherapee*'`):
```
./rawtherapee
./rawtherapee-cli
./share/man/man1/rawtherapee.1
./share/icons/hicolor/256x256/apps/rawtherapee.png
./share/icons/hicolor/64x64/apps/rawtherapee.png
./share/icons/hicolor/48x48/apps/rawtherapee.png
./share/icons/hicolor/24x24/apps/rawtherapee.png
./share/icons/hicolor/128x128/apps/rawtherapee.png
./share/icons/hicolor/16x16/apps/rawtherapee.png
./share/icons/hicolor/32x32/apps/rawtherapee.png
./share/icons/hicolor/scalable/apps/rawtherapee.svg
./share/applications/rawtherapee.desktop
./images/rawtherapee-logo-48.png
./images/rawtherapee-logo-256.png
./images/rawtherapee.ico
./images/rawtherapee-logo-128.png
./images/rawtherapee-logo-64.png
./images/rawtherapee-logo-32.png
./images/rawtherapee-logo-16.png
./images/rawtherapee-logo-24.png
```

This branch installs the following:
```
./rawtherapee
./icons/rawtherapee
./icons/rawtherapee/256x256/app_icons/rawtherapee.png
./icons/rawtherapee/64x64/app_icons/rawtherapee.png
./icons/rawtherapee/48x48/app_icons/rawtherapee.png
./icons/rawtherapee/24x24/app_icons/rawtherapee.png
./icons/rawtherapee/128x128/app_icons/rawtherapee.png
./icons/rawtherapee/16x16/app_icons/rawtherapee.png
./icons/rawtherapee/32x32/app_icons/rawtherapee.png
./icons/rawtherapee/scalable/app_icons/rawtherapee.svg
./rawtherapee-cli
./share/man/man1/rawtherapee.1
./share/applications/rawtherapee.desktop
./images/rawtherapee.ico
```

Looks like it recognizes icons in `./share/icons/hicolor/*/apps/` but not `./icons/rawtherapee/*/app_icons/`. [This page](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html) recommends having at least a 48x48 hicolor PNG icon:
> So, you're an application author, and want to install application icons so that they work in the KDE and Gnome menus. Minimally you should install a 48x48 icon in the hicolor theme. This means installing a PNG file in $prefix/share/icons/hicolor/48x48/apps.

2023-09-13 14:26 UTC, Pandagrapher commented
@Lawrence37 
Thanks for your investigations. AppImage build is now fixed.

I have performed some tests: AppImage may crash at startup with Ubuntu because this distro does not provide the `image-missing` icon with the `adwaita-icon-theme` package (installed by default). We need to install the `gnome-icon-theme` one to obtain the missing icon. This behavior does not happen with other distro as Debian (here `Adwaita` icon theme already has the icon).

IMHO we should package the `Adwaita` and `hicolor` icon theme in the AppImage to be robust to any distro/desktop. What do you think about it?

2023-09-15 04:38 UTC, Lawrence37 commented
Do you think all the icons are necessary? Checking on my computer, Adwaita is 21 MB and hicolor is 14 MB. They will be smaller in the AppImage because of compression, but they will still increase the package size by a significant percentage.

2023-09-16 17:12 UTC, Pandagrapher commented
> Do you think all the icons are necessary? Checking on my computer, Adwaita is 21 MB and hicolor is 14 MB. They will be smaller in the AppImage because of compression, but they will still increase the package size by a significant percentage.

It can be complicated to know what icons Gtk is internally using (ex: for its widgets). On a clean Ubuntu 20.04 LTS install (such as Github host), Adwaita folder is only ~4MB and hicolor one is ~3MB. It seems to be acceptable for an AppImage package.

2023-09-17 01:21 UTC, Lawrence37 commented
Ok, that's a more reasonable size. If it's necessary to include the icon themes in the AppImage, then we have no choice but to do so. I do wonder why the AppImage packaging tool doesn't automatically do it though. For GTK support, it uses [this plugin](https://github.com/linuxdeploy/linuxdeploy-plugin-gtk) which doesn't include any icons. What's the exact error that happens in Ubuntu? I looked up image-missing icon errors on the internet and all the results are problems with the OS itself.

2023-09-18 14:23 UTC, Pandagrapher commented
@Lawrence37 
Here the error message I get when running the AppImage on Ubuntu 20.04 LTS without `gnome-icon-theme` package installed:

> Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): L'icône "image-missing" n'est pas présente dans le thème rawtherapee (gtk-icon-theme-error-quark, 0)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): L'icône "image-missing" n'est pas présente dans le thème rawtherapee rawtherapee (gtk-icon-theme-error-quark, 0)

This is normal that the `image-missing` icon is not present in the `rawtherapee` theme because Gtk is expecting it to be in the `Adwaita` icon theme (`rawtherapee` icon theme is configured to use the `Adwaita` one if an icon is not present).

When searching for this error on the Internet, there is two kinds of solution:
- For a package: add dependency for the `gnome-icon-theme` package.
- For an AppImage (ex: Inkscape), packaging the `Adwaita` icon theme in the AppImage. But I agree with you, I am surprised the AppImage Gtk plugin does not manage it directly.

2023-10-07 23:17 UTC, Lawrence37 requested changes
Finally managed to review all the code. I can see you put a lot of work into this. Thanks!

2023-10-07 23:17 UTC, Lawrence37 commented on rtengine/dynamicprofile.cc
>          }
This should return false if the load fails. Something like
```c++
if (!(Glib::file_test(fileName, Glib::FILE_TEST_EXISTS) && kf.load_from_file(fileName))) {
    return false;
}
```

2023-10-07 23:17 UTC, Lawrence37 commented on rtgui/batchqueuebuttonset.cc
> +std::shared_ptr<RTSurface> BatchQueueButtonSet::tailIcon = std::shared_ptr<RTSurface>(nullptr);
No need to change anything, but just an FYI, the assignment is not necessary to create an empty shared pointer.

2023-10-07 23:17 UTC, Lawrence37 commented on rtgui/batchqueuepanel.cc
> +            grid->attach_next_to(*Gtk::manage (new RTImage ("gears-pause")), Gtk::POS_RIGHT, 1, 1);
Aren't these icons supposed to be sized with `Gtk::ICON_SIZE_LARGE_TOOLBAR`? They look a little small when using horizontal tab layouts.

2023-10-07 23:17 UTC, Lawrence37 commented on rtgui/controlspotpanel.cc
> +    balanh_(Gtk::manage(new Adjuster(M("TP_LOCALLAB_BALANH"), 0.2, 2.5, 0.1, 1.0, Gtk::manage(new RTImage("rawtherapee")), Gtk::manage(new RTImage("circle-red-green-small"))))),
The left icons don't show up (Local Adjustments > Settings > (make sure "Show additional settings" is checked) Shape detection > ab/L balance *and* C-H balance).

2023-10-07 23:17 UTC, Lawrence37 commented on rtgui/cursormanager.cc
> +            cursor_surf.getHeight() / 2 * (1. + offYb));
`2.`, or is it supposed to be integer division?

2023-10-07 23:17 UTC, Lawrence37 commented on rtgui/cursormanager.cc
> +        double offYb = std::min(std::max(-1., offY), 0.99); // offY should belong to (-1; 0.99)
It might be better to clamp the pixel coordinates instead.

2023-10-07 23:17 UTC, Lawrence37 commented on rtgui/cursormanager.cc
> +    cCropDraw   = createCursor("crop-point-hicontrast", Gdk::DIAMOND_CROSS);
Offset at -0.75, -0.75?

2023-10-07 23:17 UTC, Lawrence37 commented on rtgui/filterpanel.h
> +    std::shared_ptr<RTSurface> ornamentSurface;
The surface is not shared anywhere, so it can be a `std::unique_ptr`.

2023-10-07 23:17 UTC, Lawrence37 commented on rtgui/histogrampanel.cc
> -    int s = 8 * RTScalable::getScale();
Keep this variable but with a better name to avoid magic numbers.

2023-10-07 23:17 UTC, Lawrence37 commented on rtgui/lensprofile.cc
> +    warning(Gtk::manage(new RTImage("warning"))),
This image looks a bit small to me.

2023-10-07 23:17 UTC, Lawrence37 commented on rtgui/rtimage.cc
> +void RTImage::set_from_icon_name(const Glib::ustring& iconName)
This looks like it can be implemented with `set_from_icon_name(iconName, this->size)`.

2023-10-07 23:17 UTC, Lawrence37 commented on rtgui/rtimage.cc
> +void RTImage::set_from_gicon(const Glib::RefPtr<const Gio::Icon>& gIcon)
Similarly, this looks like `set_from_gicon(gIcon, this->size)`.

2023-10-07 23:17 UTC, Lawrence37 commented on rtgui/rtscalable.cc
> +void RTScalable::updateDPInScale(const Gtk::Window* window, double &newDPI, int &newScale)
`getDPInScale` seems like a more appropriate name.

2023-10-07 23:17 UTC, Lawrence37 commented on rtgui/rtscalable.cc
>          }
Free the `GError`.
From https://gnome.pages.gitlab.gnome.org/librsvg/Rsvg-2.0/ctor.Handle.new_from_data.html:

> In case of error, the argument will be set to a newly allocated GError; the caller will take ownership of the data, and be responsible for freeing it.

2023-10-07 23:17 UTC, Lawrence37 commented on rtgui/rtscalable.cc
> +        }
Free the `GError`.

2023-10-07 23:17 UTC, Lawrence37 commented on rtgui/rtsurface.h
> +    enum RTSurfaceType {
Make this an enum class.

2023-10-07 23:17 UTC, Lawrence37 commented on rtgui/shcselector.cc
> +        fontd.set_absolute_size (absoluteFontSize * static_cast<double>(Pango::SCALE));
The text is too large and too low especially with a large DPI and 1x scale.
![image](https://github.com/Beep6581/RawTherapee/assets/45837045/97d971e1-8c9c-4342-b586-c5e9a8e36f17)

2023-10-13 09:21 UTC, Pandagrapher commented on rtgui/cursormanager.cc
> +            cursor_surf.getHeight() / 2 * (1. + offYb));
Yes, it is supposed to be integer division

2023-10-13 09:24 UTC, Pandagrapher commented on rtgui/cursormanager.cc
> +    cCropDraw   = createCursor("crop-point-hicontrast", Gdk::DIAMOND_CROSS);
Original code:
> cAddPicker = colPickAdd     ? Gdk::Cursor::create(display, colPickAdd, (int)(4.*s), (int)(21.*s))   : Gdk::Cursor::create(display, Gdk::PLUS);

So, from a 12x12 cursor size, it needs a (-0.666, 0.75) offset to get (4, 21) coordonates (fixed it from -0.333 to -0.666)

2023-10-13 09:24 UTC, Pandagrapher commented on rtgui/histogrampanel.cc
> -    int s = 8 * RTScalable::getScale();
This variable is not needed anymore and has been removed

2023-10-13 09:26 UTC, Pandagrapher commented
@Lawrence37 Thanks for the code review :). Started taking them into account

2023-10-15 01:10 UTC, Lawrence37 commented on rtgui/cursormanager.cc
> +    cCropDraw   = createCursor("crop-point-hicontrast", Gdk::DIAMOND_CROSS);
I hadn't noticed that! However, I was referring to the crop cursor which was:
`    cCropDraw = cropDraw        ? Gdk::Cursor::create(display, cropDraw, (int)(3.*s), (int)(3.*s))      : Gdk::Cursor::create(display, Gdk::DIAMOND_CROSS);`

2023-10-20 11:17 UTC, Pandagrapher commented on rtgui/cursormanager.cc
> +    cCropDraw   = createCursor("crop-point-hicontrast", Gdk::DIAMOND_CROSS);
Fixed with commit `e3062e2`

2023-10-22 19:26 UTC, Lawrence37 approved these changes

2023-10-22 19:26 UTC, Lawrence37 commented
Looks good!

2024-03-02 23:45 UTC, Lawrence37 commented
@Pandagrapher Will this have any negative effects if part 2 is not completed before the next release? If not, then now is a good time to merge.

2024-03-03 17:27 UTC, Pandagrapher commented
> @Pandagrapher Will this have any negative effects if part 2 is not completed before the next release? If not, then now is a good time to merge.

No, there is no side effect on merging part 1 without part 2. The GUI widgets that have not been updated to handle Hi-DPI will remain "blur" (as they currently are). I gonna merge with dev during the week.

2024-03-06 18:28 UTC, Pandagrapher commented
@Lawrence37 Merge done. Feel free to accept the Pull Request when you think it's the right moment :)

2024-03-06 20:59 UTC, Lawrence37 commented
Wonderful! I see no reason to wait. 🙂

2024-03-06 20:59 UTC, merged